name: pandakey-games
services:
  # 🐼 PandaKey Games - Next.js Full-Stack App
  - name: pandakey-app
    source_dir: /
    github:
      repo: OskarFate/pandakey
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_URL
        value: ${_self.PUBLIC_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: KEYBIN_API_URL
        value: https://api.keybin.net
      - key: KEYBIN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FX_API_URL
        value: https://api.exchangerate.host/latest?base=EUR&symbols=CLP
      - key: MLC_CLIENT_ID
        value: "296927981421309"
      - key: MLC_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: MLC_REDIRECT_URI
        value: https://pandakey.games/api/ml-auth
      - key: SITE_URL
        value: https://pandakey.games
      - key: API_URL
        value: https://pandakey.games

# 🌐 Domains
domains:
  - domain: www.pandakey.games
    type: PRIMARY
    zone: pandakey.games

# 🔧 Features
features:
  - buildpack-stack=heroku-22