name: pandakey-games
services:
  # 🐼 PandaKey Games - Next.js Full-Stack App
  - name: pandakey-app
    source_dir: /
    github:
      repo: OskarFate/pandakey
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_URL
        value: ${_self.PUBLIC_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

# 🌐 Domains
domains:
  - domain: www.pandakey.games
    type: PRIMARY
    zone: pandakey.games

# 🔧 Features
features:
  - buildpack-stack=heroku-22