name: pandakey-games
services:
  # 🎨 Frontend - Next.js Store (www.pandakey.games)
  - name: frontend
    source_dir: /frontend
    github:
      repo: OskarFate/pandakey
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
      - key: NEXTAUTH_URL
        value: ${_self.PUBLIC_URL}
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET

  # ⚡ Backend - Node.js API (api.pandakey.games)
  - name: backend
    source_dir: /backend
    github:
      repo: OskarFate/pandakey
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

# 🗄️ Database
databases:
  - name: pandakey-db
    engine: MONGODB
    version: "5"

# 🌐 Domains
domains:
  - domain: www.pandakey.games
    type: PRIMARY
    zone: pandakey.games
  - domain: api.pandakey.games
    type: ALIAS
    zone: pandakey.games

# 🔧 Features
features:
  - buildpack-stack=heroku-22